zombieman:
  attack_actions:
    - PosAttack
  attack_frames:
    - 185
  empty_frames:
    - 186
    - 187
    - 189
    - 192
    - 194
    - 197
    - 198
    - 199
    - 200
    - 201
  exclusions: []

shotgunner:
  attack_actions:
    - SPosAttack
  attack_frames:
    - 218
  empty_frames:
    - 219
    - 220
    - 222
    - 225
    - 227
    - 230
    - 231
    - 232
    - 233
    - 234
  exclusions:
    - SkullAttack

archvile:
  attack_actions:
    - VileAttack
  attack_frames:
    - 264
  empty_frames:
    - 265
    - 269
    - 271
    - 274
    - 275
    - 276
    - 277
    - 278
    - 279
  exclusions:
    - SkullAttack

revenant:
  attack_actions:
    - SkelMissile
  attack_frames:
    - 341
  empty_frames:
    - 343
    - 345
    - 346
    - 349
  exclusions:
    - SkullAttack

mancubus:
  attack_actions:
    - FatAttack1
    - FatAttack2
    - FatAttack3
  attack_frames:
    - 377
    - 380
    - 383
  empty_frames:
    - 386
    - 388
    - 391
    - 392
    - 393
    - 394
    - 395
    - 396
  exclusions:
    - SkullAttack

chaingunner:
  attack_actions:
    - CPosAttack
  attack_frames:
    - 417
    - 418
  empty_frames:
    - 420
    - 422
    - 425
    - 426
    - 427
    - 429
    - 432
    - 433
  exclusions:
    - SkullAttack

imp:
  attack_actions:
    - TroopAttack
  attack_frames:
    - 454
  empty_frames:
    - 455
    - 457
    - 459
    - 462
    - 464
    - 466
    - 467
    - 468
  exclusions:
    - SkullAttack

demon:
  attack_actions:
    - SargAttack
  attack_frames:
    - 487
  empty_frames:
    - 488
    - 490
    - 492
    - 494
  exclusions: []

cacodemon:
  attack_actions:
    - HeadAttack
  attack_frames:
    - 506
  empty_frames:
    - 507
    - 509
    - 510
    - 512
    - 513
  exclusions:
    - SkullAttack

baron:
  attack_actions:
    - BruisAttack
  attack_frames:
    - 539
    - 568
  empty_frames:
    - 540
    - 542
    - 544
    - 546
    - 547
    - 569
    - 571
    - 573
    - 575
    - 576
  exclusions:
    - SkullAttack

lost_soul:
  attack_actions:
    - SkullAttack
  attack_frames:
    - 590
  empty_frames:
    - 591
    - 592
    - 593
    - 595
    - 597
    - 599
    - 600
  exclusions: []

mastermind:
  attack_actions: []
  attack_frames:
    - 616
    - 617
  empty_frames:
    - 619
    - 623
    - 624
    - 625
    - 626
    - 627
    - 628
    - 629
    - 630
  exclusions: []

arachnotron:
  attack_actions:
    - BspiAttack
  attack_frames:
    - 648
  empty_frames:
    - 634
    - 649
    - 651
    - 655
    - 656
    - 657
    - 658
  exclusions:
    - SkullAttack

cyberdemon:
  attack_actions:
    - CyberAttack
  attack_frames:
    - 685
    - 687
    - 689
  empty_frames:
    - 691
    - 693
    - 694
    - 695
    - 697
    - 698
    - 699
  exclusions:
    - SkullAttack

pain_elemental:
  attack_actions:
    - PainAttack
  attack_frames:
    - 711
  empty_frames:
    - 712
    - 714
    - 716
    - 717
    - 719
  exclusions:
    - SkullAttack

ss:
  attack_actions: []
  attack_frames:
    - 738
    - 740
  empty_frames:
    - 742
    - 744
    - 747
    - 749
    - 752
    - 753
    - 754
    - 755
    - 756
  exclusions:
    - SkullAttack
